<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>vn.edu.ds03</groupId><artifactId>ride-hailing</artifactId><version>0.1.0-SNAPSHOT</version><packaging>pom</packaging><modules><module>src/user-service</module><module>src/driver-service</module><module>src/trip-service</module><module>src/matching-service</module><module>src/payment-service</module><module>src/notification-service</module></modules></project>
